# Generated by Django 5.1.2 on 2024-10-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
