# Generated by Django 5.1.2 on 2024-10-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_uiit_price_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_naame',
            new_name='first_name',
        ),
    ]
