# Generated by Django 5.1.2 on 2024-10-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_first_naame_customer_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uiit_price',
            new_name='unit_price',
        ),
    ]
