# Generated by Django 5.1.2 on 2024-10-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_uiit_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
    ]
